### ISSUE TITLE
시스템 설계

### ISSUE THREAD

**Issue by aPatchyDev** [notBaekjun/tc-validator#2]
```
/
+- runner.py
+- expected/
|    +- stdout.txt
|    +- stderr.txt
|    +- file1.txt (as relative path)
|    +- file2.txt
|    ...
|
+- actual/
|    +- stdout.txt
|    +- stderr.txt
|
+- home/
     +- user/
          +- [사용자 실행파일]
```

실행파일의 출력 결과를 redirection으로 저장하면 `diff`를 쓸 수 있어서 이렇게 하면 괜찮을 거 같아요.

파일 권한 설정: TBD

**Comment by aPatchyDev** [comment]
권한 설정 문제

- 사용자 프로그램이 /home 밖에 있는 파일을 수정할 수 없어야 함
- runner.py가 사용자 실행파일을 사용자 권한으로 실행해야 한다
- 사용자 권한으로 실행된 사용자 프로그램은 /actual/ 경로에 출력해야 한다

여기에서 가장 간단한 해결책은 /home 밖에 있는 파일을 root 소유로 놓고 runner.py에 setuid를 주는 것이지만, interpreter script는 setuid 권한이 먹히지 않기 때문에 이 방법은 쓸 수 없겠네요. 커널 설정을 바꾸거나 solaris를 쓰면 가능하지만 이건 호환성이 떨어져서 좋지 않을 것 같아요.

일단 /expected/ 경로에 있는 파일은 절대 수정하지 못하게 해야 하니까 이거는 root 소유에 읽기 권한만 놓으면 될 것 같아요
그리고 출력은 일단 script에서 pipe로 받고 파일에 저장을 뒤로 미룰 수 있긴 한데, 그러면 /actual 대신 /tmp에 임시 경로를 쓰는 게 좋을까요?

**Comment by Tim3s** [comment]
학교 과제 상으론 출력이 꼬일 일은 없을 것 같아 임시 경로까지 구현할 필요는 없을 것 같습니다.
권한은 root에서 actual 폴더의 파일들을 생성하게 하면서, 실행파일을 subprocess로 실행해 서로 다른 권한을 주는 방식으로 하거나, home 내부에서 actual까지 생성하게 하고 root권한으로 폴더 밖으로 옮기면 되지 않을까요?

**Comment by aPatchyDev** [comment]
임시 경로를 언급한 이유는 실제 출력을 파일에 저장하기 위해서는 쓰기 권한이 필요하기 때문이에요.
저장하는 경로가 정해져 있다면 사용자 프로그램이 방해할 수 있는데 임시 폴더는 경로가 랜덤이라 간섭하기 더 어려워요.

그런데 다른 아이디어가 생각났어요. 원래 `/` 경로에 있는 파일들을 전부 하나의 폴더에 넣고 `PATH` 환경 변수도 적절히 수정하면 사용자 프로그램을 실행할 때 chroot로 격리시킬 수 있어요. 이것으로 파일 시스템을 격리하고 `runner.py`만 조심해서 만들면 사용자 프로그램의 간섭을 방지할 수 있을 거예요. 이 방안은 어떤가요?

**Comment by Tim3s** [comment]
runner.py를 제외한 파일들을 하나의 폴더 속에 넣고 runner.py를 통해 사용자 프로그램을 실행할 때 chroot로 해당 폴더 내부의 권한을 준단 말씀이시죠? 이렇게 할 거면 굳이 도커도 여러개 만들 필요 없이 여러 개의 폴더에 각각의 테스트 케이스를 넣고 각 폴더에서 사용자 프로그램을 돌리는 방식도 사용할 수 있을 것 같네요

**Comment by aPatchyDev** [comment]
테스트 케이스는 그래도 별도로 돌리는 게 편할 거예요.
```
/
+- runner.py
+- chroot/
    +- bin/
    +- usr/
    +- lib/
    +- home/
        +- user/
            +- [사용자 프로그램]
```
이렇게 하고, `PATH=/bin:/usr/bin:/chroot/bin:/chroot/usr/bin` 이렇게 환경변수도 수정해야 하는데, 여러 개의 테스트케이스를 같은 환경에서 돌리면 저 `/chroot/` 폴더를 통째로 복제해서 테스트케이스 하나 당 폴더 하나씩 만들어야 하니까요.

**실제로 chroot/를 생성하는 과정은 여러가지가 있지만 (debootstrap 등) 그거는 도커 이미지를 생성할 때의 문제라 이 모듈에서는 chroot를  쓴다는 것만 알면 되니까 일단 이렇게 진행할게요

**Comment by Tim3s** [comment]
그러면 테스트케이스는 확실히 시간이 조금 더 걸리더라도 도커를 복제하는 편이 나을 것 같네요. 수고하셨습니다!
